---
roles:
# Roles from git
  - src: https://github.com/Freggy/kubernetes-ansible.git
    version: 1.0.0
    name: freggy.kubernetes
  # Roles from galaxy
  - name: geerlingguy.containerd
    version: 1.1.1
